In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("/Users/nidagallusandeep/Downloads/employee_data.csv")

In [3]:
df.head()

   Employee_ID   Age  Experience  Salary
0          101  22.0         1.0   25000
1          102  25.0         3.0   35000
2          103  28.0         5.0   45000
3          104  30.0         NaN   55000
4          105  35.0         8.0   70000

In [4]:
df.shape

(10, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  10 non-null     int64
 1   Age          9 non-null      float64
 2   Experience   9 non-null      float64
 3   Salary       10 non-null     int64
dtypes: float64(2), int64(2)
memory usage: 452.0 bytes

In [7]:
df.isnull().sum()

Employee_ID    0
Age            1
Experience     1
Salary         0
dtype: int64

# Handle missing values

In [14]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df["Experience"]=df["Experience"].fillna(df["Experience"].mean())

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isnull().sum()

Employee_ID    0
Age            0
Experience     0
Salary         0
dtype: int64

# Select numerical features

In [19]:
X=df[["Age","Experience","Salary"]]
print(X)

         Age  Experience  Salary
0  22.000000    1.000000   25000
1  25.000000    3.000000   35000
2  28.000000    5.000000   45000
3  30.000000    8.666667   55000
4  35.000000    8.000000   70000
5  40.000000   12.000000   90000
6  45.000000   15.000000  120000
7  50.000000   20.000000  500000
8  33.555556   10.000000   80000
9  27.000000    4.000000   40000

# MinMaxScaler

In [24]:
from sklearn.preprocessing import MinMaxScaler
min_max=MinMaxScaler()
X_min_max=min_max.fit_transform(X)
print(X_min_max)

[[0.         0.         0.        ]
 [0.10714286 0.10526316 0.02105263]
 [0.21428571 0.21052632 0.04210526]
 [0.28571429 0.40350877 0.06315789]
 [0.46428571 0.36842105 0.09473684]
 [0.64285714 0.57894737 0.13684211]
 [0.82142857 0.73684211 0.2       ]
 [1.         1.         1.        ]
 [0.41269841 0.47368421 0.11578947]
 [0.17857143 0.15789474 0.03157895]]

In [27]:
minmax_df = pd.DataFrame(X_min_max,columns=["Age", "Experience", "Salary"])
minmax_df

        Age  Experience    Salary
0  0.000000    0.000000  0.000000
1  0.107143    0.105263  0.021053
2  0.214286    0.210526  0.042105
3  0.285714    0.403509  0.063158
4  0.464286    0.368421  0.094737
5  0.642857    0.578947  0.136842
6  0.821429    0.736842  0.200000
7  1.000000    1.000000  1.000000
8  0.412698    0.473684  0.115789
9  0.178571    0.157895  0.031579

# RobustScaler

In [29]:
from sklearn.preprocessing import RobustScaler
robust=RobustScaler()
X_robust=robust.fit_transform(X)
X_robust

array([[-0.85024155, -1.01149425, -0.81081081],
       [-0.58937198, -0.73563218, -0.59459459],
       [-0.32850242, -0.45977011, -0.37837838],
       [-0.15458937,  0.04597701, -0.16216216],
       [ 0.28019324, -0.04597701,  0.16216216],
       [ 0.71497585,  0.50574713,  0.59459459],
       [ 1.14975845,  0.91954023,  1.24324324],
       [ 1.58454106,  1.6091954 ,  9.45945946],
       [ 0.15458937,  0.22988506,  0.37837838],
       [-0.41545894, -0.59770115, -0.48648649]])

In [33]:
robust_df = pd.DataFrame(X_robust,columns=["Age", "Experience", "Salary"])
robust_df

        Age  Experience    Salary
0 -0.850242   -1.011494 -0.810811
1 -0.589372   -0.735632 -0.594595
2 -0.328502   -0.459770 -0.378378
3 -0.154589    0.045977 -0.162162
4  0.280193   -0.045977  0.162162
5  0.714976    0.505747  0.594595
6  1.149758    0.919540  1.243243
7  1.584541    1.609195  9.459459
8  0.154589    0.229885  0.378378
9 -0.415459   -0.597701 -0.486486

In [34]:
# Print results
print("Original Data:")
print(X)

Original Data:
         Age  Experience  Salary
0  22.000000    1.000000   25000
1  25.000000    3.000000   35000
2  28.000000    5.000000   45000
3  30.000000    8.666667   55000
4  35.000000    8.000000   70000
5  40.000000   12.000000   90000
6  45.000000   15.000000  120000
7  50.000000   20.000000  500000
8  33.555556   10.000000   80000
9  27.000000    4.000000   40000

In [35]:
print("\nMinMaxScaler:")
print(minmax_df)

MinMaxScaler:
        Age  Experience    Salary
0  0.000000    0.000000  0.000000
1  0.107143    0.105263  0.021053
2  0.214286    0.210526  0.042105
3  0.285714    0.403509  0.063158
4  0.464286    0.368421  0.094737
5  0.642857    0.578947  0.136842
6  0.821429    0.736842  0.200000
7  1.000000    1.000000  1.000000
8  0.412698    0.473684  0.115789
9  0.178571    0.157895  0.031579

In [36]:
print("\nRobustScaler:")
print(robust_df)

RobustScaler:
        Age  Experience    Salary
0 -0.850242   -1.011494 -0.810811
1 -0.589372   -0.735632 -0.594595
2 -0.328502   -0.459770 -0.378378
3 -0.154589    0.045977 -0.162162
4  0.280193   -0.045977  0.162162
5  0.714976    0.505747  0.594595
6  1.149758    0.919540  1.243243
7  1.584541    1.609195  9.459459
8  0.154589    0.229885  0.378378
9 -0.415459   -0.597701 -0.486486